[kafka]
  brokers = ["127.0.0.1:9093"]
  user = ""
  password = ""
  group = "chetki"
  topic = "flows"

[elastic]
  address = "127.0.0.1"
  port = "9200"
  geoip = false
  ipdb = "./geolite2/GeoLite2-City.mmdb"
  asndb = "./geolite2/GeoLite2-ASN.mmdb"

[mac]
  "baa43ssc4ewe" = "phone"