[kafka]
  brokers = ["127.0.0.1:9093"]
  user = ""
  password = ""
  group = "chetki"
  topic = "flows"

[elastic]
  address = "127.0.0.1"
  port = "9200"
  index = "sflow"
  geoip = false
  ipdb = "./geolite2/GeoLite2-City.mmdb"
  asndb = "./geolite2/GeoLite2-ASN.mmdb"

[mac]
  "1111" = "router"

[port]
  "443" = "https"
  "80" = "http"
  "53" = "dns"
  "993" = "imaps"


[protocol]
  "6" = "tcp"
  "17" = "udp"
  "58" = "ipv6-icmp"
  "0" = "ipv6-hop-by-hop"
  "1" = "icmp"
  "2" = "igmp"